// Derp Flipbook v3 - True Flipbook
"use strict";
const VERSION="v3-true-flipbook-1", META_KEY="derpFlipbook_v3_meta", DB_NAME="DerpFlipbookV3DB", DB_VERSION=1;
const app=document.getElementById("app"); let db,projects=[],currentId=null,current=null,canvas,ctx,onion,onionCtx,shell;
let frameIndex=0,tool="brush",drawing=false,last=null,playing=false,playTimer=null,brushSize=8,opacity=1,color="#111111",onionEnabled=true;
let viewX=0,viewY=0,viewScale=1,pointers=new Map(),panStart=null,audioObj=null;
const swatches=["#111111","#ffffff","#66d9ff","#ff6f80","#ffe66b","#82ffb2","#a78bfa","#ff9f43","#8b5e34","#f8f4e8","#555555","#000000"];
const presets=[{name:"HD Wide",w:1280,h:720},{name:"Square",w:1000,h:1000},{name:"Vertical",w:720,h:1280},{name:"Custom",w:1000,h:1000}];
const newState={name:"Untitled Flip",preset:0,w:1000,h:1000,fps:12};
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains("frames"))d.createObjectStore("frames");if(!d.objectStoreNames.contains("audio"))d.createObjectStore("audio")};r.onsuccess=()=>{db=r.result;res()};r.onerror=()=>rej(r.error)})}
function dbPut(s,k,v){return new Promise((res,rej)=>{const tx=db.transaction(s,"readwrite");tx.objectStore(s).put(v,k);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
function dbGet(s,k){return new Promise((res,rej)=>{const tx=db.transaction(s,"readonly"),r=tx.objectStore(s).get(k);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function dbDel(s,k){return new Promise((res,rej)=>{const tx=db.transaction(s,"readwrite");tx.objectStore(s).delete(k);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
function loadMeta(){try{projects=JSON.parse(localStorage.getItem(META_KEY)||"[]")}catch{projects=[]}} function saveMeta(){localStorage.setItem(META_KEY,JSON.stringify(projects))}
function uid(){return Math.random().toString(36).slice(2)+Date.now().toString(36)}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function toast(m){document.querySelector(".toast")?.remove();const t=document.createElement("div");t.className="toast";t.textContent=m;document.body.appendChild(t);setTimeout(()=>t.remove(),1700)}
function render(h){app.innerHTML=h} function clamp(n,min,max){return Math.max(min,Math.min(max,n||min))}
async function init(){await openDB();loadMeta();showHome()}
function showHome(){currentId=null;current=null;stopPlay();const cards=projects.length?projects.map(p=>`<button class="card" onclick="openProject('${p.id}')"><div class="thumb" id="thumb-${p.id}">DF</div><h3>${esc(p.name)}</h3><div class="meta">${p.frames} frames • ${p.w}×${p.h} • ${p.fps}fps</div></button>`).join(""):`<div class="meta" style="padding:24px;text-align:center">No projects yet. Make a true virtual flipbook.</div>`;
render(`<div class="screen home"><div class="brand"><button class="icon" onclick="showInfo()">☰</button><h1>Derp <span>Flipbook</span></h1><button class="icon" onclick="showImport()">⇩</button></div><div class="hero"><h2>Frame-by-frame, simple, clean.</h2><p>Draw frames, tap + to add more, use onion skin, add sound, and export tests.</p><div class="row" style="margin-top:14px"><button class="btn primary" onclick="showCreate()">New Flipbook</button><button class="btn" onclick="showImport()">Import</button></div></div><div class="projects"><div class="label">Projects</div><div class="grid">${cards}</div></div></div>`);projects.forEach(loadThumb)}
async function loadThumb(p){const el=document.getElementById("thumb-"+p.id);if(!el)return;const blob=await getFrameBlob(p.id,0);if(!blob)return;const bmp=await createImageBitmap(blob);const c=document.createElement("canvas");c.width=160;c.height=90;const x=c.getContext("2d");x.fillStyle="#f8f4e8";x.fillRect(0,0,c.width,c.height);x.drawImage(bmp,0,0,c.width,c.height);el.innerHTML="";el.appendChild(c)}
function showCreate(){const p=presets[newState.preset];if(newState.preset!==3){newState.w=p.w;newState.h=p.h}render(`<div class="screen form"><div class="topline"><button class="icon" onclick="showHome()">‹</button><b>New Flipbook</b></div><h1 class="big">Set up your flipbook.</h1><div class="field"><label>Name</label><input class="input" value="${esc(newState.name)}" oninput="newState.name=this.value"></div><div class="field"><label>Preset</label><div class="two">${presets.map((p,i)=>`<button class="btn ${newState.preset===i?'primary':''}" onclick="newState.preset=${i};showCreate()">${p.name}<br><span class="meta">${i===3?'custom size':p.w+'×'+p.h}</span></button>`).join("")}</div></div><div class="two"><div class="field"><label>Width max 3000</label><input class="input" type="number" min="64" max="3000" value="${newState.w}" oninput="newState.w=clamp(Number(this.value),64,3000)"></div><div class="field"><label>Height max 3000</label><input class="input" type="number" min="64" max="3000" value="${newState.h}" oninput="newState.h=clamp(Number(this.value),64,3000)"></div></div><div class="field"><label>FPS max 30</label><input class="input" type="number" min="1" max="30" value="${newState.fps}" oninput="newState.fps=clamp(Number(this.value),1,30)"></div><button class="btn primary" style="width:100%;font-size:20px;padding:16px" onclick="createProject()">Create</button></div>`)}
async function createProject(){const id=uid(),p={id,name:newState.name.trim()||"Untitled Flip",w:clamp(newState.w,64,3000),h:clamp(newState.h,64,3000),fps:clamp(newState.fps,1,30),frames:1,created:Date.now()};projects.unshift(p);saveMeta();await saveBlankFrame(p,0);openProject(id)}
async function saveBlankFrame(p,i){const c=document.createElement("canvas");c.width=p.w;c.height=p.h;const x=c.getContext("2d");x.fillStyle="#f8f4e8";x.fillRect(0,0,p.w,p.h);await dbPut("frames",`${p.id}:${i}`,await canvasToBlob(c))}
async function openProject(id){currentId=id;current=projects.find(p=>p.id===id);if(!current)return showHome();frameIndex=0;tool="brush";viewX=0;viewY=0;viewScale=1;audioObj=null;renderEditor();await setupCanvas();await loadFrame(0)}
function renderEditor(){render(`<div class="screen editor"><div class="editTop"><button class="icon" onclick="saveFrame().then(showHome)">‹</button><div class="projName">${esc(current.name)}</div><div class="row"><button class="icon" onclick="openProjectMenu()">⋯</button></div></div><div class="stageArea" id="stageArea"><div class="toolDock">${toolButton("brush","✎")}${toolButton("eraser","⌫")}${toolButton("fill","◼")}${toolButton("pan","✥")}</div><div class="options"><button class="btn small" onclick="toggleColor()">Color</button><input type="color" value="${color}" oninput="color=this.value"><div><div class="mini">Size</div><input type="range" min="1" max="100" value="${brushSize}" oninput="brushSize=Number(this.value)"></div><div><div class="mini">Opacity</div><input type="range" min=".05" max="1" step=".05" value="${opacity}" oninput="opacity=Number(this.value)"></div><button class="btn small" onclick="toggleOnion()">${onionEnabled?'Onion On':'Onion Off'}</button></div><div class="stageShell" id="stageShell"><canvas id="canvas"></canvas><canvas id="onion"></canvas></div></div><div class="timeline"><div class="playbar"><button class="play" onclick="togglePlay()">▶</button><div class="counter">F ${frameIndex+1}/${current.frames}</div><button class="btn small" onclick="duplicateFrame()">Duplicate</button><button class="btn small danger" onclick="deleteFrame()">Delete</button></div><div class="frameStrip" id="frameStrip">${frameStripHtml()}</div></div></div>`)}
function toolButton(id,label){return `<button class="tool ${tool===id?'active':''}" onclick="setTool('${id}')">${label}</button>`}
function frameStripHtml(){let h="";for(let i=0;i<current.frames;i++)h+=`<button class="frame ${i===frameIndex?'active':''}" data-frame="${i}" onclick="goFrame(${i})"><b>${i+1}</b></button>`;return h+`<button class="addFrame" onclick="addFrame()">+</button>`}
async function setupCanvas(){canvas=document.getElementById("canvas");ctx=canvas.getContext("2d",{willReadFrequently:true});onion=document.getElementById("onion");onionCtx=onion.getContext("2d");shell=document.getElementById("stageShell");canvas.width=current.w;canvas.height=current.h;onion.width=current.w;onion.height=current.h;const s=Math.min((innerWidth-16)/current.w,(innerHeight-245)/current.h,1);shell.style.width=(current.w*s)+"px";shell.style.height=(current.h*s)+"px";applyView();attachCanvasEvents();refreshFrameThumbs()}
async function getFrameBlob(pid,i){return await dbGet("frames",`${pid}:${i}`)}
async function loadFrame(i){frameIndex=i;const blob=await getFrameBlob(current.id,i);ctx.fillStyle="#f8f4e8";ctx.fillRect(0,0,current.w,current.h);if(blob){const bmp=await createImageBitmap(blob);ctx.drawImage(bmp,0,0)}await drawOnion();updateUIBits();refreshFrameThumbs()}
async function drawOnion(){onionCtx.clearRect(0,0,current.w,current.h);if(!onionEnabled||frameIndex<=0)return;const blob=await getFrameBlob(current.id,frameIndex-1);if(!blob)return;const bmp=await createImageBitmap(blob);onionCtx.globalAlpha=.65;onionCtx.drawImage(bmp,0,0);onionCtx.globalAlpha=1}
async function saveFrame(){if(!current||!canvas)return;await dbPut("frames",`${current.id}:${frameIndex}`,await canvasToBlob(canvas));saveMeta()}
function canvasToBlob(c,type="image/png",q=.92){return new Promise(r=>c.toBlob(r,type,q))}
function updateUIBits(){const c=document.querySelector(".counter");if(c)c.textContent=`F ${frameIndex+1}/${current.frames}`;document.querySelectorAll(".frame").forEach(f=>f.classList.toggle("active",Number(f.dataset.frame)===frameIndex))}
async function refreshFrameThumbs(){for(const btn of document.querySelectorAll(".frame")){if(btn.querySelector("canvas"))continue;const i=Number(btn.dataset.frame),blob=await getFrameBlob(current.id,i);if(!blob)continue;const bmp=await createImageBitmap(blob),c=document.createElement("canvas");c.width=104;c.height=72;const x=c.getContext("2d");x.fillStyle="#f8f4e8";x.fillRect(0,0,c.width,c.height);x.drawImage(bmp,0,0,c.width,c.height);btn.prepend(c)}}
async function goFrame(i){await saveFrame();await loadFrame(i)}
async function addFrame(){if(current.frames>=10000)return toast("10,000 frame limit reached.");await saveFrame();const insert=frameIndex+1;for(let i=current.frames-1;i>=insert;i--){const b=await getFrameBlob(current.id,i);if(b)await dbPut("frames",`${current.id}:${i+1}`,b)}current.frames++;frameIndex=insert;saveMeta();await saveBlankFrame(current,insert);renderEditor();await setupCanvas();await loadFrame(frameIndex)}
async function duplicateFrame(){await saveFrame();if(current.frames>=10000)return toast("10,000 frame limit reached.");const src=await getFrameBlob(current.id,frameIndex),insert=frameIndex+1;for(let i=current.frames-1;i>=insert;i--){const b=await getFrameBlob(current.id,i);if(b)await dbPut("frames",`${current.id}:${i+1}`,b)}current.frames++;if(src)await dbPut("frames",`${current.id}:${insert}`,src);frameIndex=insert;saveMeta();renderEditor();await setupCanvas();await loadFrame(frameIndex)}
async function deleteFrame(){if(current.frames<=1)return toast("Need at least 1 frame.");for(let i=frameIndex;i<current.frames-1;i++){const b=await getFrameBlob(current.id,i+1);if(b)await dbPut("frames",`${current.id}:${i}`,b)}await dbDel("frames",`${current.id}:${current.frames-1}`);current.frames--;frameIndex=Math.max(0,frameIndex-1);saveMeta();renderEditor();await setupCanvas();await loadFrame(frameIndex)}
function setTool(t){tool=t;renderEditor();setupCanvas().then(()=>loadFrame(frameIndex))}
function toggleOnion(){onionEnabled=!onionEnabled;drawOnion();document.querySelector(".options button:last-child").textContent=onionEnabled?"Onion On":"Onion Off"}
function toggleColor(){document.querySelector(".colorPop")?.remove();const d=document.createElement("div");d.className="colorPop";d.innerHTML=`<h3 style="margin:0 0 8px">Color Wheel</h3><input style="width:100%;height:54px" type="color" value="${color}" oninput="color=this.value"><div class="colorSwatches">${swatches.map(s=>`<button class="swatch" style="background:${s}" onclick="color='${s}';document.querySelector('.colorPop').remove()"></button>`).join("")}</div><button class="btn" style="margin-top:12px;width:100%" onclick="this.closest('.colorPop').remove()">Close</button>`;document.body.appendChild(d)}
function attachCanvasEvents(){const area=document.getElementById("stageArea");canvas.onpointerdown=e=>{e.preventDefault();canvas.setPointerCapture?.(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size>=2||tool==="pan"){panStart={x:viewX,y:viewY,pts:[...pointers.values()]};return}const p=point(e);if(tool==="fill"){ctx.save();ctx.globalAlpha=opacity;ctx.fillStyle=color;ctx.fillRect(0,0,current.w,current.h);ctx.restore();saveFrame();return}drawing=true;last=p;drawLine(p,p)};canvas.onpointermove=e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if((pointers.size>=2||tool==="pan")&&panStart){const a0=avg(panStart.pts),a1=avg([...pointers.values()]);viewX=panStart.x+(a1.x-a0.x);viewY=panStart.y+(a1.y-a0.y);applyView();return}if(!drawing)return;const p=point(e);drawLine(last,p);last=p};canvas.onpointerup=canvas.onpointercancel=e=>{pointers.delete(e.pointerId);if(pointers.size<2)panStart=null;if(drawing){drawing=false;saveFrame();refreshFrameThumbs()}};area.onwheel=e=>{e.preventDefault();const old=viewScale;viewScale=Math.max(.35,Math.min(5,viewScale*(e.deltaY<0?1.08:.92)));const r=shell.getBoundingClientRect(),mx=e.clientX-r.left,my=e.clientY-r.top;viewX-=mx*(viewScale/old-1);viewY-=my*(viewScale/old-1);applyView()}}
function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*(canvas.width/r.width),y:(e.clientY-r.top)*(canvas.height/r.height)}}function avg(ps){const s=ps.reduce((a,p)=>({x:a.x+p.x,y:a.y+p.y}),{x:0,y:0});return{x:s.x/ps.length,y:s.y/ps.length}}function applyView(){if(shell)shell.style.transform=`translate(${viewX}px,${viewY}px) scale(${viewScale})`}
function drawLine(a,b){ctx.save();ctx.lineCap="round";ctx.lineJoin="round";ctx.globalAlpha=opacity;ctx.lineWidth=brushSize;if(tool==="eraser"){ctx.globalCompositeOperation="destination-out";ctx.strokeStyle="black"}else{ctx.globalCompositeOperation="source-over";ctx.strokeStyle=color}ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.restore()}
function togglePlay(){if(playing){stopPlay();return}playing=true;let i=frameIndex;if(audioObj){audioObj.currentTime=0;audioObj.play().catch(()=>{})}playTimer=setInterval(async()=>{i++;if(i>=current.frames)i=0;await loadFrame(i)},1000/current.fps)}
function stopPlay(){playing=false;if(playTimer)clearInterval(playTimer);playTimer=null;if(audioObj)audioObj.pause()}
async function openProjectMenu(){const audioStored=await dbGet("audio",current.id);const d=document.createElement("div");d.className="drawer";d.innerHTML=`<h2>Project</h2><div class="drawerLine"><b>FPS</b><input class="input" style="width:90px" type="number" min="1" max="30" value="${current.fps}" onchange="current.fps=clamp(Number(this.value),1,30);saveMeta();toast('FPS saved')"></div><div class="drawerLine"><b>Frames</b><span>${current.frames} / 10000</span></div><div class="drawerLine"><b>Sound</b><span>${audioStored?'Attached':'None'}</span></div><input id="audioFile" class="hiddenFile" type="file" accept="audio/*" onchange="attachAudio(this.files[0])"><div class="row"><button class="btn" onclick="document.getElementById('audioFile').click()">Attach Sound</button><button class="btn" onclick="loadAudio()">Load Sound</button></div><div class="row" style="margin-top:10px"><button class="btn primary" onclick="exportVideo()">Export Video</button><button class="btn" onclick="exportProject()">Backup JSON</button><button class="btn danger" onclick="this.closest('.drawer').remove()">Close</button></div><p class="meta">Export uses browser recording. If MP4 is not supported, it exports WebM. GIF export is planned after the core editor is stable.</p>`;document.body.appendChild(d)}
async function attachAudio(file){if(!file)return;await dbPut("audio",current.id,file);toast("Sound attached.");loadAudio()}async function loadAudio(){const b=await dbGet("audio",current.id);if(!b)return toast("No sound attached.");if(audioObj)URL.revokeObjectURL(audioObj.src);audioObj=new Audio(URL.createObjectURL(b));toast("Sound loaded for preview.")}
async function exportVideo(){await saveFrame();const rc=document.createElement("canvas");rc.width=current.w;rc.height=current.h;const rctx=rc.getContext("2d"),mime=MediaRecorder.isTypeSupported("video/mp4")?"video/mp4":"video/webm",stream=rc.captureStream(current.fps),chunks=[],rec=new MediaRecorder(stream,{mimeType:mime});rec.ondataavailable=e=>chunks.push(e.data);rec.onstop=()=>{const blob=new Blob(chunks,{type:mime}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`${safeFile(current.name)}.${mime.includes("mp4")?"mp4":"webm"}`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);toast("Export done.")};toast("Recording export...");rec.start();let i=0;const timer=setInterval(async()=>{const blob=await getFrameBlob(current.id,i);rctx.fillStyle="#f8f4e8";rctx.fillRect(0,0,current.w,current.h);if(blob){const bmp=await createImageBitmap(blob);rctx.drawImage(bmp,0,0)}i++;if(i>=current.frames){clearInterval(timer);setTimeout(()=>rec.stop(),120)}},1000/current.fps)}
async function exportProject(){await saveFrame();const frames=[];for(let i=0;i<current.frames;i++){const blob=await getFrameBlob(current.id,i);frames.push(blob?await blobToDataURL(blob):null)}const data=JSON.stringify({version:VERSION,project:current,frames},null,2),blob=new Blob([data],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`${safeFile(current.name)}_dfv3.json`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}
function showImport(){const d=document.createElement("div");d.className="drawer";d.innerHTML=`<h2>Import Backup</h2><textarea id="importText" placeholder="Paste Derp Flipbook v3 JSON backup..."></textarea><div class="row"><button class="btn primary" onclick="importProject()">Import</button><button class="btn danger" onclick="this.closest('.drawer').remove()">Close</button></div>`;document.body.appendChild(d)}
async function importProject(){try{const data=JSON.parse(document.getElementById("importText").value),p=data.project;p.id=uid();p.name=(p.name||"Imported")+" copy";projects.unshift(p);saveMeta();for(let i=0;i<data.frames.length;i++){if(data.frames[i])await dbPut("frames",`${p.id}:${i}`,dataURLToBlob(data.frames[i]))}document.querySelector(".drawer")?.remove();openProject(p.id)}catch{toast("Import failed.")}}
function blobToDataURL(blob){return new Promise(res=>{const fr=new FileReader();fr.onload=()=>res(fr.result);fr.readAsDataURL(blob)})}function dataURLToBlob(url){const [head,body]=url.split(","),mime=head.match(/:(.*?);/)[1],bin=atob(body),arr=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)arr[i]=bin.charCodeAt(i);return new Blob([arr],{type:mime})}
function showInfo(){const d=document.createElement("div");d.className="drawer";d.innerHTML=`<h2>Derp Flipbook v3</h2><p>True virtual flipbook build. Simple frame-by-frame drawing, onion skin, up to 10,000 frames, custom canvas up to 3000×3000, 30 FPS, sound preview, and browser video export.</p><p class="meta">Tip: two fingers pans the canvas. Use the + button to add frames.</p><button class="btn primary" onclick="this.closest('.drawer').remove()">Cool</button>`;document.body.appendChild(d)}
function safeFile(s){return String(s||"derp_flipbook").replace(/[^a-z0-9_-]+/gi,"_")}if("serviceWorker"in navigator)navigator.serviceWorker.register("service-worker.js").catch(()=>{});init();
